# -*- coding: utf-8 -*-
"""csv_to_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P7NAJKMlqeYiULR8zxwotChw5Fi-Y_1L
"""

def read_csv():
  import pandas as pd
  data=[]
  df = pd.read_csv('ptt_title.csv', encoding = 'utf8')
  a = df['title']
  for i in a:
    data.append(i[0:-2])
  return data