# -*- coding: utf-8 -*-
"""pttpage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QRWf0nbjM-MqF8n3-cq4B7QaIj6Yi5aW
"""

import requests
import re
from bs4 import BeautifulSoup
import pandas as pd

title=[]
payload={
    'from':'/bbs/Gossiping/index.html',
    'yes':'yes'
}
rs = requests.session()
pttpage = rs.post('https://www.ptt.cc/ask/over18',verify=False,data=payload)

for page in range(38969,38869,-1):
  pttpage = rs.get("https://www.ptt.cc/bbs/Gossiping/index"+str(page)+'.html',verify=False)
  main = BeautifulSoup(pttpage.text)

  for t in main.select('.r-ent'):
    y = t.select('.title')[0].text
    if '刪除)' not in y:
      y = y.split(']')
      title.append(y[-1])

print(title)
df=pd.DataFrame({'title':title})
df.to_csv('ptt_title.csv', index=False)